// Builds the inline SVG icon sprite in index.html from Phosphor Icons (MIT).
// To add an icon: find its name at https://phosphoricons.com, add it below,
// run `npm run build:icons`, then reference it with
//   <svg class="icon size-5" aria-hidden="true"><use href="#i-NAME"/></svg>
// Bold weight is used for UI glyphs; duotone ("-duo" ids) for feature icons.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const assets = join(root, "node_modules/@phosphor-icons/core/assets");

const ICONS = {
  bold: [
    "phone", "chat-circle-dots", "clipboard-text", "arrow-right", "check",
    "pause", "play", "map-pin", "copy",
  ],
  duotone: [
    // Platinum
    "lightning", "wrench", "tag",
    // Services
    "engine", "snowflake", "fan", "armchair", "speaker-high", "package",
    // Policies
    "timer", "truck", "arrow-counter-clockwise", "warehouse", "calendar-x", "warning",
    // Winterization
    "calendar-check", "chat-text", "clipboard-text",
  ],
};

const symbols = [];
for (const [weight, names] of Object.entries(ICONS)) {
  for (const name of names) {
    const svg = readFileSync(join(assets, weight, `${name}-${weight}.svg`), "utf8");
    const inner = svg
      .replace(/^[\s\S]*?<svg[^>]*>/, "")
      .replace(/<\/svg>\s*$/, "")
      .replace(/<rect width="256" height="256" fill="none"\/>/g, "")
      .trim();
    const id = weight === "duotone" ? `i-${name}-duo` : `i-${name}`;
    symbols.push(`    <symbol id="${id}" viewBox="0 0 256 256">${inner}</symbol>`);
  }
}

const sprite = [
  "<!-- icons:start (generated by scripts/build-icons.mjs; do not edit by hand) -->",
  '  <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" style="position:absolute;width:0;height:0;overflow:hidden">',
  ...symbols,
  "  </svg>",
  "  <!-- icons:end -->",
].join("\n");

const htmlPath = join(root, "index.html");
const html = readFileSync(htmlPath, "utf8");
const pattern = /<!-- icons:start[\s\S]*?<!-- icons:end -->/;
if (!pattern.test(html)) {
  throw new Error("index.html is missing the <!-- icons:start --> ... <!-- icons:end --> markers");
}
writeFileSync(htmlPath, html.replace(pattern, sprite));
console.log(`Wrote ${symbols.length} icons into index.html`);
